### ISSUE TITLE
Unable To Build

### ISSUE THREAD

**Issue by mischov** [Overbryd/myhtmlex#1]
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)

### Steps
1. `git clone git@github.com:Overbryd/myhtmlex.git`
2. `cd myhtmlex`
3. `mix deps.get`
4. `mix compile`

### First Problem

Mix file has `CFLAGS += -Werror` enabled, meaning warnings cause errors. I get a lot of the following warnings:

```
In file included from deps/myhtml/source/myhtml/myosi.h:25:0,
                 from deps/myhtml/source/myhtml/myhtml.h:29,
                 from src/myhtmlex.h:7,
                 from src/myhtmlex.c:1:
deps/myhtml/source/mycore/myosi.h:120:1: warning: âtypedefâ is not at beginning of declaration [-Wold-style-declaration]
 typedef mycore_status_t;
 ^
```

Can comment out `CFLAGS += -Werror` to proceed

### Second Problem

```
/usr/bin/ld: /tmp/ccMMc0rw.o: relocation R_X86_64_32 against `nif_cleanup_myhtmlex_ref' can not be used when making a shared object; recompile with -fPIC
/tmp/ccMMc0rw.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:39: recipe for target 'priv/myhtmlex.so' failed
make: *** [priv/myhtmlex.so] Error 1

```

I don't know enough about c to understand why that is happening, but when I try to recompile with -fPIC compilation succeeds. Unfortunately, then running `mix test` causes a segfault.

**Comment by Overbryd** [comment]
Thanks for reporting the issue. I am developing on a Darwin system, so I had Linux not yet on my radar.
Now there is also a `build-test/` directory, containing a Ubuntu 16.04 Docker build that should match your system specification.

Would you mind verifying that `master@8aa4376` works on your system?
If not, I am more than happy to reopen this issue or accept a Pull Request with a broken Dockerfile to work with.

Kind regards,

Lukas

**Comment by mischov** [comment]
It works.

**Comment by Overbryd** [comment]
![](https://media.tenor.com/images/80fcf7b0a1b8c43a0047b14e9ea9b7e6/tenor.gif)
