### ISSUE TITLE
Error Compiling

### ISSUE THREAD

**Issue by mischov** [Overbryd/myhtmlex#3]
Error seems to have been introduced in 630db71.

### Steps

1. `git clone git@github.com:Overbryd/myhtmlex.git`
2. `cd myhtmlex`
3. `mix deps.get`
4. `mix compile` 

### Result

```
/usr/bin/make -C c_src/myhtml library
make[1]: Entering directory '...snip.../myhtmlex/c_src/myhtml'
make[1]: *** No rule to make target 'library'.  Stop.
make[1]: Leaving directory '...snip.../myhtmlex/c_src/myhtml'
Makefile:51: recipe for target 'c_src/myhtml/lib/libmyhtml_static.a' failed
make: *** [c_src/myhtml/lib/libmyhtml_static.a] Error 2
Compiling 2 files (.ex)
Generated myhtmlex app
```
Then (since make failed?):
```
10:51:38.452 [warn]  The on_load function for module Elixir.Myhtmlex.Decoder returned:
{{:badmatch,
  {:error,
   {:load_failed,
    'Failed to load NIF library: \'...snip.../myhtmlex/_build/dev/lib/myhtmlex/priv/myhtmlex.so: cannot open shared object file: No such file or directory\''}}},
 [{Myhtmlex.Decoder, :init, 0, [file: 'lib/myhtmlex/decoder.ex', line: 9]},
  {:code_server, :"-handle_on_load/5-fun-0-", 1,
   [file: 'code_server.erl', line: 1333]}]}


10:51:38.462 [error] Process #PID<0.143.0> raised an exception
** (MatchError) no match of right hand side value: {:error, {:load_failed, 'Failed to load NIF library: \'...snip.../myhtmlex/_build/dev/lib/myhtmlex/priv/myhtmlex.so: cannot open shared object file: No such file or directory\''}}
    lib/myhtmlex/decoder.ex:9: Myhtmlex.Decoder.init/0
    (kernel) code_server.erl:1333: anonymous fn/1 in :code_server.handle_on_load/5
```

**Comment by Overbryd** [comment]
Oh. Yep sorry about that, master is currently unstable as I change things and move forward.

Possible workarounds for your problem:

    $ git submodule update

Or try going back one revision before compiling.

**Comment by mischov** [comment]
The error was introduced 5 commits back and is present in the hex package.

**Comment by Overbryd** [comment]
Thank for checking that.
I think I found the problem, and I will keep testing it with a hex-package build test.

So for some reason it is important for `mix` to have the `priv` directory present when compiling, so it symlinks the directory next to the resulting build files.

I did not realise that, because in my local working directory priv was always present.
Now the latest hex package `0.1.3` and the `master` should be fine again.

**Comment by mischov** [comment]
Ah, I am sorry for not making clear the fact that priv and previous compilations were hiding the error. The reason I gave the steps for reproducing the way I did was because it creates a fresh directory with no previous compilation, but I neglected to mention *why* I was doing that.

Package on Hex now works. :+1:
