### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by Overbryd** [Overbryd/myhtmlex#5]
This issue holds all open tasks for a 0.2.0 hex release.
Branch: https://github.com/Overbryd/myhtmlex/tree/v0.2

#### Outline

Since supporting NIFs only is a bit too risky for most of the projects that might use this library, providing C-Node is probably the best in terms of crash-safety and speed.

This release adds support for switching between NIFs and "Safe" (C-Node) mode.

In order to provide the best experience to the user, I am using [Nodex](https://github.com/Overbryd/nodex) to put the C-Node under supervision. Basically, calling  `Myhtmlex.Safe.decode/2` provides the very same experience as calling into `Myhtmlex.Nif.decode/2`.

#### Acceptance criteria

- [x] provide `Myhtmlex.Safe` module as an equivalent to `Myhtmlex.Nif`
- [x] default to `Myhtmlex.Safe` when requiring this dependency
- [x] test both implementations
- [x] Documentation
- [x] Update README
- [x] Hex package tests

**Comment by Overbryd** [comment]
@f34nk if you would like to add something to this release, comment here. I planned to finalise this over this weekend.

**Comment by f34nk** [comment]
Ubuntu 14.04
Erlang/OTP 20 [erts-9.2]
Elixir 1.6.1 
gcc version 4.8.5
branch: v0.2

Hi, I checked all installation steps. Except this minor [PR](https://github.com/Overbryd/myhtmlex/pull/6) everything works as expected. Also documentation and README looks up to date to me.
I like the changes you made for this branch. Putting cnode before NIF is the propper thing to do IMO.

**Comment by Overbryd** [comment]
Thanks. I now released [`0.2.0-rc1`](https://hex.pm/packages/myhtmlex/0.2.0-rc1) and it seems to work just fine.

Except my package tests break, but because of some upstream error. I opened up an [issue here](https://github.com/hexpm/hex/issues/515)

After I get this resolved, I will be releasing `0.2.0`.
